services:
  csohelper-postgres:
    image: postgres:15
    restart: always
    env_file:
      - envs/postgres.env
    volumes:
      - ./storage/pgdata/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    ports:
      - "5432:5432"

  csohelper-redis:
    image: redis:7
    restart: always
    env_file:
      - envs/redis.env
    volumes:
      - ./storage/redis:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    env_file:
      - envs/bot-api.env
    volumes:
      - ./storage/tgapi/:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

  csohelper-nginx:
    image: nginx:latest
    restart: always
    env_file:
      - envs/nginx.env
    volumes:
      - ./storage/tgapi/:/var/lib/telegram-bot-api:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8082:80"
    depends_on:
      telegram-bot-api:
        condition: service_started

  csohelper-bot:
    build: .
    restart: always
    env_file:
      - envs/bot.env
    volumes:
      - ./storage/bot/:/app/storage/
    depends_on:
      csohelper-postgres:
        condition: service_healthy
      csohelper-redis:
        condition: service_healthy
      csohelper-nginx:
        condition: service_started